# Generated by Django 3.2.7 on 2021-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.FileField(blank=True, default=None, null=True, upload_to='keys/'),
        ),
    ]
