# Generated by Django 3.2.7 on 2021-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_profile_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, unique=True)),
                ('public_key', models.BinaryField(null=True)),
            ],
        ),
    ]
