# Generated by Django 3.2.7 on 2021-09-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Center',
        ),
    ]
