# Generated by Django 3.2.7 on 2021-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0009_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='public_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='private_key',
            field=models.BinaryField(null=True),
        ),
    ]
