# Generated by Django 3.2.7 on 2021-09-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210914_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
