# Generated by Django 3.2.7 on 2021-10-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encrypt_hash',
            field=models.BinaryField(null=True),
        ),
    ]
