# Generated by Django 3.2.7 on 2021-10-15 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0004_alter_message_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('name_tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_sequence', models.IntegerField(blank=True, default=None, null=True)),
                ('nextus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextus', to=settings.AUTH_USER_MODEL)),
                ('prevus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prevus', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='road', to='mail.road')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='')),
                ('tags', models.ManyToManyField(blank=True, default=None, related_name='tags', to='mail.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='RouteMessageJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message_id', to='mail.message')),
                ('next_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to=settings.AUTH_USER_MODEL)),
                ('prev_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prev_user', to=settings.AUTH_USER_MODEL)),
                ('route_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='road_id', to='mail.road')),
            ],
        ),
    ]
