# Generated by Django 3.2.7 on 2021-10-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20211010_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='spam',
            new_name='is_favourite',
        ),
    ]
