# Generated by Django 3.2.7 on 2021-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_road_routemessagejournal_tags_templates_userinroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='message',
            name='in_route',
            field=models.BooleanField(default=False),
        ),
    ]
