# Generated by Django 3.2.7 on 2021-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_rename_spam_message_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_trully_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
