# Generated by Django 3.2.7 on 2021-10-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20211015_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
