# Generated by Django 3.2.7 on 2021-10-07 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='route',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
