# Generated by Django 3.2.7 on 2021-10-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_message_is_trully_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_trully_deleted',
            new_name='is_truly_deleted',
        ),
    ]
