# Generated by Django 3.2.7 on 2021-10-07 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_road_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='route',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
