# Generated by Django 3.2.7 on 2021-10-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encrypt_hash',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_truly_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
