# Generated by Django 3.2.7 on 2021-10-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_rename_is_trully_deleted_message_is_truly_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
    ]
