# Generated by Django 3.2.7 on 2021-10-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0010_auto_20211008_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmessagejournal',
            name='next_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roadmessagejournal',
            name='prev_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prev_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
