# Generated by Django 3.2.7 on 2021-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_auto_20211008_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmessagejournal',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='roadmessagejournal',
            name='next_user',
        ),
        migrations.RemoveField(
            model_name='roadmessagejournal',
            name='prev_user',
        ),
        migrations.AlterField(
            model_name='file',
            name='encrypt_hash',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Road',
        ),
        migrations.DeleteModel(
            name='RoadMessageJournal',
        ),
    ]
