# Generated by Django 3.2.7 on 2021-10-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_auto_20211008_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
