# Generated by Django 3.2.7 on 2021-10-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0016_road_user_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='user_in_route',
        ),
    ]
