# Generated by Django 3.2.7 on 2021-10-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0018_message_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadMessageJournal',
        ),
    ]
