# Generated by Django 3.2.7 on 2021-10-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0024_remove_routemessagejournal_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemessagejournal',
            name='route_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='road_id', to='mail.road'),
        ),
    ]
