# Generated by Django 3.2.7 on 2021-10-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0025_routemessagejournal_route_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='user_route',
        ),
        migrations.AddField(
            model_name='road',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserInRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_sequence', models.IntegerField(blank=True, default=None, null=True)),
                ('nextus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextus', to=settings.AUTH_USER_MODEL)),
                ('prevus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prevus', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='road', to='mail.road')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
