# Generated by Django 3.2.7 on 2021-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0027_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('name_tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='templates',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='tags', to='mail.Tags'),
        ),
    ]
